### ISSUE TITLE
Toast Notifications not working with XAML islands

### ISSUE THREAD

**Issue by kaustubh1994** [windows-toolkit/Microsoft.Toolkit.Win32#121]
## I'm submitting a...

Bug Report - I am trying to generate simple toast notifications for my Windows application targeting .NETCORE 3.0. I have included the following NuGet packages into my project:
1. Microsoft.Toolkit.Uwp.Notifications
2. Microsoft.Toolkit.Wpf.UI.XamlHost

## Current behavior
An unhandled exception gets thrown "System.Exception: 'Element not found. (0x80070490)'" along with the message ''System.Private.CoreLib.pdb not loaded". 
This exception is thrown when the following code nippet is hit: ToastNotificationManager.CreateToastNotifier().Show(toast);

## Stack Trace
   at Windows.UI.Notifications.ToastNotificationManager.CreateToastNotifier()
   at ToastChecker.MainWindow.SendToastNotification() in C:\git\Toast\ToastChecker\MainWindow.xaml.cs:line 53
   at ToastChecker.MainWindow.MainWindow_ContentRendered(Object sender, EventArgs e) in C:\git\Toast\ToastChecker\MainWindow.xaml.cs:line 38
   at System.Windows.Window.OnContentRendered(EventArgs e)
   at System.Windows.Window.<PostContentRendered>b__202_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at ToastChecker.App.Main()

Exception Method - Windows.UI.Notifications.ToastNotifier CreateToastNotifier()

## Expected behavior
I expect a simple toast notification to be shown when my project is run.

## Minimal reproduction of the problem with instructions
I have attached a sample project, which is showing the same behavior as mentioned above.
[ToastChecker.zip](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/files/3184476/ToastChecker.zip)

## Environment
```
Nuget Package(s): 
1. Microsoft.Toolkit.Uwp.Notifications [5.1.1]
2. Microsoft.Toolkit.Wpf.UI.XamlHost [6.0.0-preview5]

Windows 10 Build Number:
[x] Insider Build (build number: 18362.113)

App min and target version:
[x] Insider Build (18362.0)

Device form factor:
[x] Desktop

Visual Studio 
[x] 2019 (version: 16.0.3)


```

**Comment by azchohfi** [comment]
You don't need to manually reference the windows.winmd facade anymore. Version 6.0.0-preview4 added the https://www.nuget.org/packages/Microsoft.Windows.SDK.Contracts/10.0.18362.2002-preview nuget package, which adds the WinMDs for you.
The ToastNotificationManager requires an App ID, so you need to be packaged inside an MSIX/APPX or use a com server which is a little bit tricky, but works.
We have an unmerged PR that should help with that (https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/2793)
And here is the docs:
https://github.com/MicrosoftDocs/WindowsCommunityToolkitDocs/pull/179

You can also use the current docs on this, which does not use the WCT version of the helper:
https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop

**Comment by kaustubh1994** [comment]
Our requirements specify that we support Windows 7 and up, hence I cannot use the MSIX path. Since I am using .net core, using the COM server is also not an option since it is supported only for .NET framework. Is there a workaround for this, I am only interested in generating simple toast notifications and nothing complex. What would you suggest in this case?

**Comment by AaronRobinsonMSFT** [comment]
@kaustubh1994 Managed COM servers are supported on .NET Core, but as mentioned the programmatic approach is no longer supported. Instead the path has been designed to match the classic COM approach using `regsvr32.exe`. A sample of this has been placed under https://docs.microsoft.com/en-us/dotnet/samples-and-tutorials/#samples-1.
