### ISSUE TITLE
Webview control not working in Window 10 Enterprise Virtual Desktop Instance.Version 1903, Build 18362.175

### ISSUE THREAD

**Issue by baskialdensys** [windows-toolkit/Microsoft.Toolkit.Win32#143]
## I'm submitting a...
 Bug report (I searched for similar issues and did not find one) -->  

## Expected behavior
We have an app using WebView control and trying to use it in Windows 10 Enterprise Virtual Desktop instance and OS version is higher than April 2018 Fall creator update. WebView control is not working as expected

## Environment
 Windows 10 Virtual Desktop Instance
 Version 1903, Build 18362.175

Nuget Package(s): 

Package Version(s): 

Windows 10 Build Number:
 Version 1903, Build 18362.175

Device form factor:
- [ ] Desktop

Visual Studio 
- [ ] 2019 (version: )

**Comment by verelpode** [comment]
Hi @baskialdensys.  When you use Virtual Desktop instance, do you have it configured in a manner that causes Windows Explorer ("explorer.exe") NOT to run?

Can you confirm whether or not your issue is the same as my issue #165 -- WPF WebView crashes when "explorer.exe" is not running.

**Comment by verelpode** [comment]
I investigated this issue further because it's also relevant in our environment.  I discovered that this desktops bug is NOT the same bug as #165.   The cause of the desktops bug is that WPF WebView launches WWAHost.exe in the Default desktop instead of launching it in the same desktop as the app using WebView.  

WWAHost.exe creates a HWND but this HWND fails to appear because it is in the desktop named "Default", whereas the HWND can only appear if it is the same desktop as the app using WebView.  Thus to fix this bug, `Windows.Web.UI.Interop.WebViewControlProcess` needs to check what desktop the current app is inside, and ensure that the WWAHost.exe instance is launched in that same desktop, instead of always launching in the default desktop.

Here are steps to reproduce the desktops bug:

1. Write a small test WPF app that displays WebView and navigates to a webpage.
2. Write another program that executes the Win32 [CreateDesktop](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createdesktopw) and [SwitchDesktop](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-switchdesktop) functions.
3. In the new desktop, launch an instance of "explorer.exe".  This instance of the explorer.exe process should be running inside the newly created desktop.
4. By using the mouse (meaning this step does not have to be performed programmatically), use the GUI of explorer.exe to launch the aforementioned WPF app that displays WebView and navigates to a webpage.
5. Observe that the WPF app doesn't crash and doesn't throw any exception, but the WebView remains blank (white) and fails to display the webpage.
6. Observe that the WebView instance did launch an instance of WWAHost.exe but in the wrong desktop.  The WWAHost.exe instance is running in the desktop named "Default" instead of the newly created desktop where the app + WebView is located.

Note that the bug cannot be reproduced by using the so-called "desktops" feature that is available by clicking the "Task View" icon located immediately right of the Start menu icon in Windows 10 (Pro and Enterprise).  That feature does not create the same kind of "desktop" as what the Win32 [CreateDesktop](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createdesktopw) function creates.  I think the "desktops" in "Task View" operate by hiding and showing windows, not by creating `HDESK` instances.  Thus WebView experiences no problems with multiple "desktops" created via "Task View".  In contrast, in certain enterprise environments and in certain RDP scenarios etc, multiple `HDESK` desktops exist and this is where WebView fails.

So, in response to what @baskialdensys reported, we say "me too".  We would much appreciate a bugfix that makes `WebViewControlProcess` launch the WWAHost instance in the correct desktop, meaning the same desktop as the app using `WebView`, not always the default desktop.

**Comment by baskialdensys** [comment]
I believe in our case it might be failing at IsWorkstation check. For some reason Windows 10 Virtual multi User edition might be reporting as server workstation. 

Due to our project deadline, we moved our code to use CefSharp browser control. We would love to use WebView  control and keep things simple.

**Comment by baskialdensys** [comment]
Here is the exception from event viewer
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Resources.MissingManifestResourceException
at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(System.String)
at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(System.Globalization.CultureInfo, System.Collections.Generic.Dictionary`2<System.String,System.Resources.ResourceSet>, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
at System.Resources.ResourceManager.InternalGetResourceSet(System.Globalization.CultureInfo, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
at System.Resources.ResourceManager.InternalGetResourceSet(System.Globalization.CultureInfo, Boolean, Boolean)
at System.Resources.ResourceManager.GetString(System.String, System.Globalization.CultureInfo)
at Microsoft.Toolkit.Win32.UI.Controls.DesignerUI.get_E_NOTSUPPORTED_OS_RS4()
at Microsoft.Toolkit.Win32.UI.Controls.Interop.OSVersionHelper.ThrowIfBeforeWindows10April2018()
at Microsoft.Toolkit.Wpf.UI.Controls.WebView.Initialize()
at Microsoft.Toolkit.Wpf.UI.Controls.WebViewHost.BuildWindowCore(System.Runtime.InteropServices.HandleRef)

**Comment by baskialdensys** [comment]
E_NOTSUPPORTED_OS_RS4() that leads to IsWorkstation check

**Comment by verelpode** [comment]
Oh OK!  So apparently my wild guess was incorrect, but I ended up discovering another bug anyway.  In that case, I'm going to open a separate new issue for the `CreateDesktop` bug, which is relevant to our environment.
