### ISSUE TITLE
The specified module could not be found - "System.Private.CoreLib"

### ISSUE THREAD

**Issue by chanallenk** [windows-toolkit/Microsoft.Toolkit.Win32#206]
## Describe the bug
In Windows 10 1909, apps using Xaml Islands with custom UWP controls in WPF are throwing the exception "The specified module could not be found. (0x8007007E)". With source = "System.Private.CoreLib". This exception occurs in the XamlApplication project. 

I followed the exact steps in this link. If you go to section [Create a XamlApplication object](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands#create-a-xamlapplication-object-in-a-uwp-app-project), the issue occurs in the code shown on step 5 when debugging the app:

`
namespace MyUWPApp
{
    public sealed partial class App : Microsoft.Toolkit.Win32.UI.XamlHost.XamlApplication
    {
        public App()
        {
            this.Initialize();
        }
    }
}
`

Exception occurs on constructor. (Sorry I don't know why the code snippet tool is not working)

Stacktrace:

>    at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
   at Microsoft.Toolkit.Win32.UI.XamlHost.XamlApplication..ctor()
   at BlankApp.App..ctor() in C:\Users\AC\source\repos\XAMLIslandTest\MyUWPApp\App.xaml.cs:line 26

I believe the issue is related to Windows 10 1909 since I tested the project on two other machines running 1903 with the same version of Visual Studio with no issues. 

- [ ] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work:

## Steps to Reproduce
1. Use a machine with Windows 10 1909
2. Create or use an existing simple Xaml Island application. I followed the exact same instructions [here](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands)

## Expected behavior
No errors occur and UWP control is hosted properly in the project.

## Environment

```
NuGet Package(s): 
1. Microsoft.Toolki.Wpf.UI.XamlHost
2. Microsoft.VCRTForwarders.140

Package Version(s): 
1. v6.0.0
2. v1.0.2-rc

Project .NET Version:
- [ ] .NET Framework (version: )
- [X] .NET Core 3
- [ ] .NET Core 3.1 Preview (version: )

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [X] October 2019 Update
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [X] May 2019 Update (18362)
- [ ] Insider Build (xxxxx)

Device form factor:
- [X] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [X] 2019 (version: 16.3.10) 
- [ ] 2019 Preview (version: )

```

## Additional context
I tested two different projects (one very large, one small), each one tested on 3 machines with same Visual Studio Profesional v16.3.10:
1. Windows 10 Pro N 1903 - No Issues
2. Windows 10 Enterprise 1903 - No issues
3. Windows 10 Pro 1909 - Issue

**Comment by chanallenk** [comment]
Issue seems to be fixed in the latest Visual Studio release 16.4.0.
