### ISSUE TITLE
Manifest error in Xaml Islands + Clickonce deploy

### ISSUE THREAD

**Issue by airannarvaez** [windows-toolkit/Microsoft.Toolkit.Win32#242]
Hi, I have a problem with the deploy of a Winforms application with XamlIslands, when using Clickonce.
![image](https://user-images.githubusercontent.com/16393469/76227018-6bb70c80-61fd-11ea-8ce5-33cdcbc90171.png)

Installed NuGet:
> Microsoft.Toolkit.Forms.UI.Controls v6.0.0.0
> Microsoft.Toolkit.Forms.UI.XamlHost v6.0.0.0
> Microsoft.Windows.SDK.Contracts v10.0.18362.2005

This is the complete error it presents to me.
```
PLATFORM VERSION INFO
	Windows 			: 10.0.18362.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.3752.0 built by: NET48REL1
	clr.dll 			: 4.8.4121.0 built by: NET48REL1LAST_C
	dfdll.dll 			: 4.8.3752.0 built by: NET48REL1
	dfshim.dll 			: 10.0.18362.1 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Users/Airan/source/repos/WindowsFormsApp11/WindowsFormsApp11/publish/WindowsFormsApp11.application

IDENTITIES
	Deployment Identity		: WindowsFormsApp11.application, Version=1.0.0.2, Culture=neutral, PublicKeyToken=ead899326265eab6, processorArchitecture=msil

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\Airan\source\repos\WindowsFormsApp11\WindowsFormsApp11\publish\WindowsFormsApp11.application resulted in exception. Following failure messages were detected:
		+ Exception reading manifest from file:///C:/Users/Airan/source/repos/WindowsFormsApp11/WindowsFormsApp11/publish/Application%20Files/WindowsFormsApp11_1_0_0_2/WindowsFormsApp11.exe.manifest: the manifest may not be valid or the file could not be opened.
		+ The manifest is missing required hashes for some application components. The manifest signature is regarded as not valid.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [3/9/2020 11:23:17] : Activation of C:\Users\Airan\source\repos\WindowsFormsApp11\WindowsFormsApp11\publish\WindowsFormsApp11.application has started.
	* [3/9/2020 11:23:17] : Processing of deployment manifest has successfully completed.
	* [3/9/2020 11:23:17] : Installation of the application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [3/9/2020 11:23:17] System.Deployment.Application.InvalidDeploymentException (ManifestParse)
		- Exception reading manifest from file:///C:/Users/Airan/source/repos/WindowsFormsApp11/WindowsFormsApp11/publish/Application%20Files/WindowsFormsApp11_1_0_0_2/WindowsFormsApp11.exe.manifest: the manifest may not be valid or the file could not be opened.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Deployment.Application.InvalidDeploymentException (SignatureValidation)
		- The manifest is missing required hashes for some application components. The manifest signature is regarded as not valid.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.Manifest.AssemblyManifest.ValidateSignature(Stream s)
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.
```
Code:
>https://github.com/airannarvaez/TestXamlIslandsClickonce/

**Comment by michael-hawker** [comment]
@marb2000 @ocalvo any thoughts?

**Comment by marb2000** [comment]
Unfortunately ClickOnce is an unsupported scenario. The recommendation is using MSIX.
