### ISSUE TITLE
XAML Island (WindowsXamlHost) does not work with multiple WPF Windows.

### ISSUE THREAD

**Issue by azchohfi** [windows-toolkit/Microsoft.Toolkit.Win32#26]
## I'm submitting a...
- Bug report (I searched for similar issues and did not find one) 

## Current behavior
In WPF, if you have multiple Windows and try to use the WindowsXamlHost in more than one of them, when you try to create the control on the new window, it will crash with the following error:
```
System.Runtime.InteropServices.COMException
  HResult=0x80004005
  Message=Unspecified error

AttachToWindow method failed because the specified HWND descends from a different top-level window than the HWND that was previously passed to AttachToWindow on the same thread. See: https://go.microsoft.com/fwlink/?linkid=875497
  Source=Microsoft.Toolkit.Wpf.UI.XamlHost
  StackTrace:
   at Microsoft.Toolkit.Win32.UI.XamlHost.IDesktopWindowXamlSourceNative.AttachToWindow(IntPtr parentWnd)
   at Microsoft.Toolkit.Wpf.UI.XamlHost.WindowsXamlHostBase.BuildWindowCore(HandleRef hwndParent)
   at Microsoft.Toolkit.Wpf.UI.XamlHost.WindowsXamlHost.BuildWindowCore(HandleRef hwndParent)
   at System.Windows.Interop.HwndHost.BuildWindow(HandleRef hwndParent)
   at System.Windows.Interop.HwndHost.BuildOrReparentWindow()
   at System.Windows.Interop.HwndHost.OnSourceChanged(Object sender, SourceChangedEventArgs e)
   at System.Windows.SourceChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.PresentationSource.UpdateSourceOfElement(DependencyObject doTarget, DependencyObject doAncestor, DependencyObject doOldParent)
   at System.Windows.PresentationSource.OnVisualAncestorChanged(DependencyObject uie, AncestorChangedEventArgs e)
   at System.Windows.UIElement.OnVisualAncestorChanged(Object sender, AncestorChangedEventArgs e)
   at System.Windows.Media.Visual.ProcessAncestorChangedNotificationRecursive(DependencyObject e, AncestorChangedEventArgs args)
   at System.Windows.Media.Visual.ProcessAncestorChangedNotificationRecursive(DependencyObject e, AncestorChangedEventArgs args)
   at System.Windows.Media.Visual.FireOnVisualParentChanged(DependencyObject oldParent)
   at System.Windows.Media.Visual.AddVisualChild(Visual child)
   at System.Windows.FrameworkElement.set_TemplateChild(UIElement value)
   at System.Windows.Controls.ContentPresenter.UseContentTemplate.BuildVisualTree(FrameworkElement container)
   at System.Windows.StyleHelper.ApplyTemplateContent(UncommonField`1 dataField, DependencyObject container, FrameworkElementFactory templateRoot, Int32 lastChildIndex, HybridDictionary childIndexFromChildID, FrameworkTemplate frameworkTemplate)
   at System.Windows.FrameworkTemplate.ApplyTemplateContent(UncommonField`1 templateDataField, FrameworkElement container)
   at System.Windows.FrameworkElement.ApplyTemplate()
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Documents.AdornerDecorator.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Border.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Window.MeasureOverrideHelper(Size constraint)
   at System.Windows.Window.MeasureOverride(Size availableSize)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Interop.HwndSource.set_RootVisual(Visual value)
   at System.Windows.Window.SetRootVisual()
   at System.Windows.Window.SetRootVisualAndUpdateSTC()
   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.CreateSourceWindowDuringShow()
   at System.Windows.Window.SafeCreateWindowDuringShow()
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at WpfIslandsMultipleWindowApp.MainWindow.<>c.<WindowsXamlHost_ChildChanged>b__1_0(Object s, RoutedEventArgs args) in C:\Users\alzollin\source\repos\WpfIslandsMultipleWindowApp\WpfIslandsMultipleWindowApp\MainWindow.xaml.cs:line 21
```

## Expected behavior
XAML Islands work on multiple WPF Windows, even if they are running on the same thread. Managing multiple UI Threads is a lot of work, and most of the times, unnecessary.

## Minimal reproduction of the problem with instructions
Just create a new WPF project, add the nugets, add the UWP WinMDs and Runtime dlls. Add a simple WindowsXamlHost to the MainWindow and make it's InitialTypeName="Windows.UI.Xaml.Controls.Button". The hook up to the ChildChanged event, like this:
```
private void WindowsXamlHost_ChildChanged(object sender, EventArgs e)
{
    if (((WindowsXamlHost)sender).Child is Windows.UI.Xaml.Controls.Button button)
    {
        button.Content = "Open new Window";
        button.Click += (s, args) =>
        {
            var mainWindow = new MainWindow();
            mainWindow.Show();
        };
    }
}
```
It will crash with the aforementioned exception.

## Environment

```
Nuget Package(s): Microsoft.Toolkit.Wpf.UI.XamlHost

Package Version(s): 5.0.0-preview.gb86cb1c4cb

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [X] Insider Build (build number: 18252)

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [X] October 2018 Update (17763)
- [ ] Insider Build (xxxxx)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [X] 2017 (version: 15.8.6)
- [ ] 2017 Preview (version: )

```

**Comment by chanallenk** [comment]
I have found that it works when creating the window in a new thread. However, upon closing that new window, the application crashes, I'm assuming because it is unable to properly dispose the XAML Island components.

**Comment by azchohfi** [comment]
@marb2000 has this been fixed already?
