### ISSUE TITLE
Faulting application name: wwahost.exe, version: 10.0.19041.488, time stamp: 0x64bdb2d5

### ISSUE THREAD

**Issue by rhavlick** [windows-toolkit/Microsoft.Toolkit.Win32#299]
Hello,

We have a customer who is running Windows 10 20H2.  Edge and IE both launch fine.  We've then embedded the WebViewCompatible control in our WinForms application.

When our application attempts to open the WebViewCompatible the app crashes because of wwahost.exe is crashing.  When we run our application as Administrator then everything runs fine.

Does anyone know why this is failing?

**Windows Event Viewer .NET Runtime Error:**
Log Name:      Application
Source:        Application Error
Date:          1/7/2021 4:32:27 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      
Description:
Faulting application name: wwahost.exe, version: 10.0.19041.488, time stamp: 0x64bdb2d5
Faulting module name: KERNELBASE.dll, version: 10.0.19041.662, time stamp: 0xec58f015
Exception code: 0xc0000409
Fault offset: 0x000000000010bd5c
Faulting process id: 0x1978
Faulting application start time: 0x01d6e544f8f6b569
Faulting application path: C:\Windows\System32\wwahost.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 5d883caa-63f9-4241-8497-2ef062601e3a
Faulting package full name: Microsoft.Win32WebViewHost_10.0.19041.423_neutral_neutral_cw5n1h2txyewy
Faulting package-relative application ID: DPI.Unaware
Event Xml:
<Truncated>

Here is our stack trace:
Application: MyTestapp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Windows.Web.UI.Interop.WebViewControlProcess.add_ProcessExited(Windows.Foundation.TypedEventHandler`2<Windows.Web.UI.Interop.WebViewControlProcess,System.Object>)
   at System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal+NativeOrStaticEventRegistrationImpl.AddEventHandler[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`2<System.__Canon,System.Runtime.InteropServices.WindowsRuntime.EventRegistrationToken>, System.Action`1<System.Runtime.InteropServices.WindowsRuntime.EventRegistrationToken>, System.__Canon)
   at System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.AddEventHandler[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`2<System.__Canon,System.Runtime.InteropServices.WindowsRuntime.EventRegistrationToken>, System.Action`1<System.Runtime.InteropServices.WindowsRuntime.EventRegistrationToken>, System.__Canon)
   at Microsoft.Toolkit.Win32.UI.Controls.Interop.WinRT.WebViewControlHost.SubscribeProcessExited()
   at Microsoft.Toolkit.Win32.UI.Controls.Interop.WinRT.WebViewControlHost..ctor(Windows.Web.UI.Interop.WebViewControl)
   at Microsoft.Toolkit.Win32.UI.Controls.Interop.WinRT.WebViewControlProcess+<CreateWebViewControlHostAsync>d__16.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.Toolkit.Forms.UI.Controls.WebViewControlProcessExtensions.CreateWebViewControlHost(Microsoft.Toolkit.Win32.UI.Controls.Interop.WinRT.WebViewControlProcess, IntPtr, System.Drawing.Rectangle)
   at Microsoft.Toolkit.Forms.UI.Controls.WebView.Initialize()
   at Microsoft.Toolkit.Forms.UI.Controls.WebView.System.ComponentModel.ISupportInitialize.EndInit()
   at Microsoft.Toolkit.Forms.UI.Controls.WebViewCompatibilityAdapter.Initialize()
   at Microsoft.Toolkit.Forms.UI.Controls.WebViewCompatible..ctor()

**Comment by rhavlick** [comment]
Thank you - yes - WebView2 does work - we were just wondering if anyone knew how to fix this on WebView1.  Thanks again.
