### ISSUE TITLE
System.TypeLoadException when OnWindowLocationChanged occurs

### ISSUE THREAD

**Issue by KexyBiscuit** [windows-toolkit/Microsoft.Toolkit.Win32#73]
## I'm submitting a...

- Bug report (I searched for similar issues and did not find one)
 

## Current behavior

```
System.TypeLoadException
  HResult=0x80131522
  Message=Could not find Windows Runtime type 'Windows.UI.Xaml.XamlRoot'.
  Source=Microsoft.Toolkit.Wpf.UI.XamlHost
  StackTrace:
   at Microsoft.Toolkit.Wpf.UI.XamlHost.WindowsXamlHostBase.OnWindowLocationChanged(Object sender, EventArgs e)
   at System.Windows.Window.OnLocationChanged(EventArgs e)
   at System.Windows.Window.WmMoveChangedHelper()
   at System.Windows.Window.WmMoveChanged()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

## Expected behavior

No exception is thrown.

## Minimal reproduction of the problem with instructions

1. Create a new WPF App (.NET Core).
2. Install Microsoft.Toolkit.Wpf.UI.XamlHost 6.0.0-build.16.
3. Add following code to MainWindow.xaml. Unrelated code is omitted.

```
<Window xmlns:XamlHost="clr-namespace:Microsoft.Toolkit.Wpf.UI.XamlHost;assembly=Microsoft.Toolkit.Wpf.UI.XamlHost">
    <Grid>
        <XamlHost:WindowsXamlHost InitialTypeName="Windows.UI.Xaml.Controls.TimePicker />
    </Grid>
</Window>
```

## Environment

```
Nuget Package(s): Microsoft.Toolkit.Wpf.UI.XamlHost

Package Version(s): 6.0.0-build.16

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [x] October 2018 Update (17763)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] Insider Build (xxxxx)
- [x] netcoreapp3.0

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )
- [x] 2019 Preview (version: 16.0.0 Preview 2.0)

```

**Comment by michael-hawker** [comment]
@azchohfi know who should look at this?

**Comment by marb2000** [comment]
I requires to add an app manifest within the property <maxversiontested Id="10.0.18295.0"/>. Take a look to the samples.

After doing it, no repro.

**Comment by KexyBiscuit** [comment]
@marb2000 Could you please explain how to do it? I tried adding an application manifest file, but nothing changes.

**Comment by devsko** [comment]
@marb2000 @azchohfi I have the exact same behavior. Adding app.manifest didn't change anything. I had a look into the assembly (from 6.0.0-build.16) and found the method `private void OnWindowLocationChanged(object sender, EventArgs e)` which references XamlRoot and cannot work prior 19H1. It seems that this version is built from the rel/6.0.0 branch and that it has some incomplete merges.

**Comment by marb2000** [comment]
Have you tried to add the  <maxversiontested Id="10.0.18295.0" section/> to the app manifest? For instance:
https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/blob/master/Microsoft.Toolkit.Sample.Wpf.App/app.manifest

**Comment by devsko** [comment]
Yes, I tried and double checked. 
I had to add <ApplicationManifest> Property to .csproj by hand because VS 2019 doesnt add it. I am not sure if the .NET Core Build actually use it.
I dont know exactly what the manifest does but the assembly references a type that is new in sdk 18298. (I use 17763).
