### ISSUE TITLE
MarshalDirectiveException when binding to ObservableCollection<>

### ISSUE THREAD

**Issue by devsko** [windows-toolkit/Microsoft.Toolkit.Win32#92]
## I'm submitting a...

 - Bug report (I searched for similar issues and did not find one)  
 

``` c#
        private void WindowsXamlHost_Initialized(object sender, EventArgs e)
        {
            var collection = new ObservableCollection<object>();
            var list = new WUX.Controls.ListBox();
            list.ItemsSource = collection;
            xamlHost.Child = list;
            collection.Add(new object());
        }
```

## Current behavior

`collection.Add()` throws
```
System.Runtime.InteropServices.MarshalDirectiveException: 'Cannot marshal 'parameter #2': Error 0x2608.  Debugging resource strings are unavailable. See http://go.microsoft.com/fwlink/?linkid=106663&Version=4.0.30319.0&File=mscorrc.dll&Key=0x2608'
   at System.StubHelpers.StubHelpers.ThrowInteropParamException(Int32 resID, Int32 paramIdx)
   at System.Runtime.InteropServices.WindowsRuntime.NotifyCollectionChangedEventArgsMarshaler.CreateNativeNCCEventArgsInstanceHelper(Int32 action, IntPtr newItem, IntPtr oldItem, Int32 newIndex, Int32 oldIndex)
   at System.Runtime.InteropServices.WindowsRuntime.NotifyCollectionChangedEventArgsMarshaler.ConvertToNative(NotifyCollectionChangedEventArgs managedArgs)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at WpfApp8.MainWindow.WindowsXamlHost_Initialized(Object sender, EventArgs e)
   at System.Windows.FrameworkElement.RaiseInitialized(EventPrivateKey key, EventArgs e)
   at System.Windows.FrameworkElement.OnInitialized(EventArgs e)
   at Microsoft.Toolkit.Wpf.UI.XamlHost.WindowsXamlHostBase.OnInitialized(EventArgs e)
   at System.Windows.FrameworkElement.TryFireInitialized()
   at System.Windows.FrameworkElement.EndInit()
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
```

## Expected behavior

Should work. The exact same code works in UWP.

## Environment

```
Microsoft.Toolkit.Wpf.UI.XamlHost (private build from branch 6.0.0 @ 1dbafae)
Windows Preview 10.0.18351.0
Windows SDK 10.0.18342.0
.NET Core 3.0.100-preview3-010431
VS 2019 Preview 4.1
```

**Comment by devsko** [comment]
Also tracked here https://github.com/dotnet/corefx/issues/35909

**Comment by devsko** [comment]
Fixed in https://github.com/dotnet/corefx/pull/36224
