### ISSUE TITLE
MissingMethodException get_XamlRoot()

### ISSUE THREAD

**Issue by Zangl** [windows-toolkit/Microsoft.Toolkit.Win32#95]
## I'm submitting a...
Bug report (I searched for similar issues and did not find one)

## Current behavior
If I use WindowsXamlHost in my WPF app and maximize or minimize the window I get a MissingMethodException.

Stack trace - 

Maximize or Minimize the app produces - System.MissingMethodException
HResult=0x80131513
Message=Method not found: 'Windows.UI.Xaml.XamlRoot Windows.UI.Xaml.UIElement.get_XamlRoot()'.
Source=Microsoft.Toolkit.Wpf.UI.XamlHost
StackTrace:
at Microsoft.Toolkit.Wpf.UI.XamlHost.WindowsXamlHostBase.OnWindowLocationChanged(Object sender, EventArgs e)
at System.Windows.Window.OnLocationChanged(EventArgs e)
at System.Windows.Window.WmMoveChangedHelper()
at System.Windows.Window.WmMoveChanged()
at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

## Expected behavior
Normal window resizing behaviour.

## Minimal reproduction of the problem with instructions
Take the simple WPF app, add the WindowsXamlHost control, build and run, click maximize.
[see sample app https://github.com/Microsoft/XamlIslandBlogPostSample] this has the same issue for me at least.

## Environment

```
Nuget Package(s): 

Package Version(s): 

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [x] October 2018 Update (17763)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [x] October 2018 Update (17763)
- [ ] Insider Build (xxxxx)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [x] 2017 (version:15.9.7)
- [ ] 2017 Preview (version: )

```

**Comment by michael-hawker** [comment]
@azchohfi have you seen this before and/or have time to try and repro today?

**Comment by michael-hawker** [comment]
Thanks @Zangl for the report, we're you using the 5.1 nuget package?  It'd be good to know if this happens on the latest Insider build and with the 6.0 preview package.  Xaml Islands was still in preview for 17763, so some of these issues may be resolved.

**Comment by Zangl** [comment]
I'm using 6.0.0-preview1, to repro, clone XamlIslandBlogPostSample and maximize when running. Breaks for me with the MissingMethodException

**Comment by devsko** [comment]
I am pretty sure Windows 17763 won't be supported in version 6. XAML islands kind of worked but have been marked experimental in windows prior 19H1. XamlRoot is a new API and important for XAML islands to work correctly. I think there should be a better message when using version 6 on unsupported windows versions. See also #73

**Comment by lhak** [comment]
Have you tried upgrading to preview3? It seems that the preview1 branch contains some xamlroot related code, but it is not in the preview3 branch.

**Comment by michael-hawker** [comment]
This should be fixed in the newer preview packages.
